### ISSUE TITLE
log versus slog

### ISSUE THREAD

**Issue by emk** [production-rs/bikeshed#3]
The list looks great!

In my experience, the standard choice of logging crate in the Rust world is `log`, not `slog`. In particular, key libraries like `hyper` and `postgres` make heavy use of `log` internally, and this information is vital for debugging production apps.

I think `slog` has some `log` compatibility, and it might be the best choice for more complicated logging needs. But I would personally recommend `log`, with a footnote saying "see `slog` if you need more sophisticated structured logging", if only because `log` is used by so many critical libraries.

**Comment by stephanbuys** [comment]
@emk agreed, I think structured logging can actually be a valid category in its own right. At some point more motivation and reasoning per crate should be added to the repo, but for now I'm just going to run with this.

(Fixed in https://github.com/production-rs/bikeshed/commit/b391a610af5ceebb2399637f84e1945da262845b)
